BEGINFILE {
    itl_map["check_apt"]["-t"] = "apt_timeout"	    	    
    itl_map["check_apt"]["-u"] = "apt_upgrade"
    itl_map["check_apt"]["-d"] = "apt_dist_upgrade" 		
    itl_map["check_apt"]["-i"] = "apt_include"
    itl_map["check_apt"]["-e"] = "apt_exclude"	    	    
    itl_map["check_apt"]["-c"] = "apt_critical"
    itl_map["check_apt"]["-o"] = "apt_only_critical"

    itl_map["check_by_ssh"]["-H"] = "by_ssh_address"    	
    itl_map["check_by_ssh"]["-p"] = "by_ssh_port"
    itl_map["check_by_ssh"]["-C"] = "by_ssh_command"    	
    itl_map["check_by_ssh"]["-l"] = "by_ssh_logname"
    itl_map["check_by_ssh"]["-i"] = "by_ssh_identity"   	
    itl_map["check_by_ssh"]["-q"] = "by_ssh_quiet"
    itl_map["check_by_ssh"]["-w"] = "by_ssh_warn"	    	
    itl_map["check_by_ssh"]["-c"] = "by_ssh_crit"
    itl_map["check_by_ssh"]["-t"] = "by_ssh_timeout"    	
    itl_map["check_by_ssh"]["-o"] = "by_ssh_option"
    itl_map["check_by_ssh"]["-4"] = "by_ssh_ipv4"	    	
    itl_map["check_by_ssh"]["-6"] = "by_ssh_ipv6"
    itl_map["check_by_ssh"]["-E"] = "by_ssh_skip_stderr"	

    itl_map["check_dig"]["-H"] = "dig_server"               
    itl_map["check_dig"]["-p"] = "dig_port"
    itl_map["check_dig"]["-l"] = "dig_lookup"               
    itl_map["check_dig"]["-T"] = "dig_record_type"	        
    itl_map["check_dig"]["-w"] = "dig_warning"		        
    itl_map["check_dig"]["-c"] = "dig_critical"
    itl_map["check_dig"]["-t"] = "dig_timeout"		        
    itl_map["check_dig"]["-4"] = "dig_ipv4"
    itl_map["check_dig"]["-6"] = "dig_ipv6"                 
    itl_map["check_dig"]["-A"] = "dig_arguments"

    itl_map["check_disk"]["-e"] = "disk_errors_only"		
    itl_map["check_disk"]["-E"] = "disk_exact_match"
    itl_map["check_disk"]["-p"] = "disk_partition"		    
    itl_map["check_disk"]["-w"] = "disk_wfree"
    itl_map["check_disk"]["-c"] = "disk_cfree"		        
    itl_map["check_disk"]["-W"] = "disk_inode_wfree"
    itl_map["check_disk"]["-K"] = "disk_inode_cfree"		
    itl_map["check_disk"]["-x"] = "disk_partitions_excluded"
    itl_map["check_disk"]["-g"] = "disk_group"		        
    itl_map["check_disk"]["-f"] = "disk_ignore_reserved"
    itl_map["check_disk"]["-k"] = "disk_kilobytes"		    
    itl_map["check_disk"]["-l"] = "disk_local"
    itl_map["check_disk"]["-M"] = "disk_mountpount"		    
    itl_map["check_disk"]["-m"] = "disk_megabytes"
    itl_map["check_disk"]["-A"] = "disk_all"		        
    itl_map["check_disk"]["-t"] = "disk_timeout"
    itl_map["check_disk"]["-R"] = "disk_eregi_path"		    
    itl_map["check_disk"]["-r"] = "disk_ereg_path"
    itl_map["check_disk"]["-I"] = "disk_iginore_eregi_path"	
    itl_map["check_disk"]["-i"] = "disk_ereg_path"
    itl_map["check_disk"]["-t"] = "disk_timeout"		    
    itl_map["check_disk"]["-u"] = "disk_units"
    itl_map["check_disk"]["-X"] = "disk_exclude_type"

    itl_map["check_http"]["-H"] = "http_address"    		
    itl_map["check_http"]["-I"] = "http_vhost"
    itl_map["check_http"]["-w"] = "http_warn"	    	    
    itl_map["check_http"]["-c"] = "http_crit"
    itl_map["check_http"]["-s"] = "http_ssl"

    itl_map["check_snmp"]["-H"] = "snmp_host"	    	    
    itl_map["check_snmp"]["-C"] = "snmp_community"
    itl_map["check_snmp"]["-o"] = "snmp_oid"	    	    
    itl_map["check_snmp"]["-w"] = "snmp_warn"
    itl_map["check_snmp"]["-c"] = "snmp_crit"
}
